apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    {{- include "webhook-site.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
