{{- if not .Values.webhook.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-site-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: webhook-site
    {{- include "webhook-site.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.webhook.env.APP_KEY | quote }}
{{- end }}
