apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: webhook-site
    {{- include "webhook-site.labels" . | nindent 4 }}
spec:
  selector:
    app: webhook-site
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
